services:
  db:
    image: postgres:17
    container_name: postgres_id3_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: id3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
