import { CreateSongMetadataDto } from '../dto/create-song-metadata.dto';

export const songMetadataExample: CreateSongMetadataDto = {
  title: 'Bohemian Rhapsody',
  artists: ['Queen'],
  albumArtist: 'Queen',
  albums: ['A Night at the Opera'],
  years: [1975],
  genres: ['Rock'],
  trackNumber: 11,
  discNumber: 1,
  duration: '5:55',
  bitrate: '320kbps',
  sampleRate: '44.1kHz',
  channels: 2,
  encoder: 'LAME 3.99',
  fileSize: '5MB',
  composers: ['Freddie Mercury'],
  conductors: ['Brian May'],
  publisher: 'EMI',
  copyright: '© 1975 Queen Productions Ltd.',
  isrc: 'GBUM71029604',
  bpm: 72,
  key: 'Bb Major',
  mood: 'Epic',
  language: 'English',
  comments: 'One of the greatest songs ever.',
  lyrics: 'Is this the real life? Is this just fantasy?...',
  paths: ['/music/queen/bohemian_rhapsody.mp3'],
  playCount: 42,
  rating: 5,
  lastModified: new Date().toISOString(),
};
